name: playlist
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
#  sdk: ^3.7.2 - replaced for right formatting last comma

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  share_plus: ^11.0.0
  flutter_email_sender: ^7.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: YS Display
      fonts:
        - asset: assets/fonts/ys_display_medium.ttf
          weight: 500
        - asset: assets/fonts/ys_display_regular.ttf
          weight: 400

flutter_intl:
  enabled: true
